### ISSUE TITLE
Error at pancake-swap-v1-bsc-testnet/pancake-swap-interface-v1/src/state/index.ts

### ISSUE THREAD

**Issue by JustPandaEver** [laptrinhbockchain/pancake-swap-v1-bsc-testnet#1]
TypeScript error in /root/pancake-swap-v1-bsc-testnet/pancake-swap-interface-v1/src/state/index.ts(43,3):
Type 'MergedState' is not assignable to type '{ application?: { blockNumber: { [x: number]: number | undefined; }; popupList: { key: string; show: boolean; content: { txn: { hash: string; success: boolean; summary?: string | undefined; }; } | { listUpdate: { ...; }; }; removeAfterMs: number | null; }[]; walletModalOpen: boolean; settingsMenuOpen: boolean; } | u...'.
  Types of property 'user' are incompatible.
    Type '{ [key: string]: any; }' is missing the following properties from type '{ lastUpdateVersionTimestamp?: number | undefined; userDarkMode: boolean | null; matchesDarkMode: boolean; userExpertMode: boolean; userSlippageTolerance: number; userDeadline: number; tokens: { ...; }; pairs: { ...; }; timestamp: number; audioPlay: boolean; }': userDarkMode, matchesDarkMode, userExpertMode, userSlippageTolerance, and 5 more.  TS2322

    41 |   },
    42 |   middleware: [...getDefaultMiddleware({ thunk: false }), save({ states: PERSISTED_KEYS })],
  > 43 |   preloadedState: loadedState,
       |   ^
    44 | })
    45 | 
    46 | store.dispatch(updateVersion())

**Comment by laptrinhbockchain** [comment]
I have checked this bug. This error arises due to the new version of the library "@reduxjs/toolkit".
To fix this bug, you need remove current version of the library "@reduxjs/toolkit" and install version "1.3.5":
```
npm remove @reduxjs/toolkit
npm install @reduxjs/toolkit@1.3.5
```
