### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by MarquisOgre** [laptrinhbockchain/pancake-swap-v1-bsc-testnet#10]
The yarn start was working fine till 3 days back but today when i git clone the repo, yarn install and yarn start gives me this failed to compile error. Some help on this issue is really appreciated 

![image](https://user-images.githubusercontent.com/39271918/133449172-107c4673-4791-4dc6-b932-0f3cb5b72a62.png)

**Comment by laptrinhbockchain** [comment]
I think it has to do with the libraries version. You can try copying the entire node_modules folder of the working version to new version.

**Comment by IamAshrafSyed** [comment]
Try jus replacing the src folder of working version with the src folder of not working version.

**Comment by Dream1027** [comment]
I am building this repository, but I have a same error.
@kiemtienonline360 , could you send me the entire node_modules folder of the working version ?

**Comment by 90hacker** [comment]
I am building this repository, but I have a same error.
@kiemtienonline360 , could you send me the entire node_modules folder of the working version ?

**Comment by Dream1027** [comment]
Who's this ?

**Comment by laptrinhbockchain** [comment]
**node_modules** for **win**: https://drive.google.com/file/d/1FfgKKWBA7eXzP9UiNBLDi55bRYg27zBo/view?usp=sharing
(Node v14.15.0 and Windows 10)
