### ISSUE TITLE
Cannot swap and get my liquid pool

### ISSUE THREAD

**Issue by hoanghoo** [laptrinhbockchain/pancake-swap-v1-bsc-testnet#2]
I already deploy this project. But after I create pool (create pair), I cannot get my pool. I also swap with my pool with message "Insufficient liquidity for this trade" but when check in Contract Factory what contained my pair

FACTORY: 0x1D25344336023f0fCcd63eb1230594C906d64f21
INIT_CODE_HASH: 0xd593df08b8c5f17942cd8e7bc8ff4487de43014cfde91a86c02578fd7279b215
ROUTER: 0x60C86646bd236eCA70957fcC54adC80716Ae4354
WBNB: 0xae13d989dac2f0debff460ac112a837c89baa7cd

**Comment by laptrinhbockchain** [comment]
Your contracts look like okie. The problem maybe in the "**pancake-swap-interface-v1**".
Do you re-check "**Modify source code**" part, especially the correction in **@pancakeswap-libs**

**Comment by khanhk99** [comment]
Mình cũng gặp lỗi tương tự và đã check kỹ trong @pancakeswap-libs

**Comment by laptrinhbockchain** [comment]
> Mình cũng gặp lỗi tương tự và đã check kỹ trong @pancakeswap-libs

Bạn có public site không, gửi mình link mình kiểm tra được ko?

**Comment by khanhk99** [comment]
https://gitlab.com/khanhk99/binanswap.git 
trong folder pancake-swap
factory testnet: 0x0c0884cE72a64f21C55897be8c31eD64047eF2c4
router testnet: 0x0332aCD7D0eD3a0ED17D59c1df0746435D0820d3

Bạn xem giúp mình với. Thanks

**Comment by Medicyp** [comment]
Hi guys. I have the same issue. Have you managed to solve it?

**Comment by khanhk99** [comment]
@Medicyp
I solve it after following this guide: https://github.com/nhancv/pancake-swap-testnet#readme
I think you have to deploy both Router01 and Router02, then replace address in "src/state/swap/hooks.ts" or replace anywhere have address of Router01 and Router02

**Comment by Medicyp** [comment]
Thanks it works now!
