### ISSUE TITLE
issue when in set language

### ISSUE THREAD

**Issue by SkroooB** [laptrinhbockchain/pancake-swap-v1-bsc-testnet#4]
`pancake-swap-interface-v1/src/components/Menu/index.tsx
TypeScript error in D:/pancakeswap/pan_test/pancake-swap-v1-bsc-testnet/pancake-swap-interface-v1/src/components/Menu/index.tsx(29,7):
Type '{ code: string; language: string; }[]' is not assignable to type 'Language[]'.
  Property 'locale' is missing in type '{ code: string; language: string; }' but required in type 'Language'.  TS2322

    27 |       toggleTheme={toggleTheme}
    28 |       currentLang={selectedLanguage?.code || ''}
  > 29 |       langs={allLanguages}
       |       ^
    30 |       setLang={setSelectedLanguage}
    31 |       cakePriceUsd={cakeBusdPrice}
    32 |       profile={profile}`

**Comment by laptrinhbockchain** [comment]
You can use other version at here: https://github.com/nhancv/pancake-swap-testnet#readme
