### ISSUE TITLE
UPLOAD THE APP TO A TRADITIONAL HOSTING

### ISSUE THREAD

**Issue by OnlimakeFinance** [laptrinhbockchain/pancake-swap-v1-bsc-testnet#6]
I have managed to integrate into local and it works on localhost: 3000.

Now I don't know how to upload this app to a traditional hosting without having to use wws or my pc on 24/7.

Can someone explain to me please

**Comment by JustPandaEver** [comment]
just make a static file and upload it use command `yarn build`

**Comment by OnlimakeFinance** [comment]
Sorry for my lack of experience but I can't get the app to appear in:

http://finance.onlimake.com

I have uploaded the files in zip to the host but I don't see the app working as it does on localhost: 3000

**Comment by JustPandaEver** [comment]
Already done unzip your file and change file permission to 777?

**Comment by laptrinhbockchain** [comment]
> Sorry for my lack of experience but I can't get the app to appear in:
> 
> http://finance.onlimake.com
> 
> I have uploaded the files in zip to the host but I don't see the app working as it does on localhost: 3000

After uploading the zip file to the host, you must unzip it.

**Comment by OnlimakeFinance** [comment]
error :

yarn build
yarn run v1.22.5
warning ..\..\package.json: No license field
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Cannot find module 'C:\xxxx\xxxx\xxxx\pancake-swap-interface-v1\node_modules\webpack\node_modules\is-extendable\index.js'. Please verify that the package.json has a valid "main" entry


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
