### ISSUE TITLE
Error: "expected even number of hex-nibbles"

### ISSUE THREAD

**Issue by gabenitez0** [laptrinhbockchain/pancake-swap-v1-bsc-testnet#8]
Hola!
En el paso 2.2, cuando cambio el hex al INIT_CODE_PAIR_HASH generado, recibo el error: "expected even number of hex-nibbles".
![image](https://user-images.githubusercontent.com/21694696/128665917-48db0924-d2bb-49c5-8ff8-4552f28de23c.png)

...de hecho, si utilizo el código que aparece en la guía, también recibo el mismo error:
![image](https://user-images.githubusercontent.com/21694696/128666018-b3c6ef57-5be0-4255-8f1c-88135510e597.png)

Si intento compilar todo así como está, el remix también me devuelve el mismo error:
![image](https://user-images.githubusercontent.com/21694696/128666179-738a6c66-c246-4a67-813f-9b9d132c14b3.png)

Intenté sacar el '0x' del inicio y todo funcionó correctamente, logre iniciar el proyecto, pero el exchange no calcula el trade ni tampoco permite realizarlo. Lo cierto es que igual no sé si esta es la causa del problema pero es el unico error que tuve en el proceso.

Cuando inicio el proyecto habiendo eludido el error, la consola del Google Chrome devuelve estos errores:
![image](https://user-images.githubusercontent.com/21694696/128666440-94b718e5-90d7-45a3-9a8b-08b284281dd4.png)

Desde ya muchas gracias!

------- ENGLISH
Hi there!
In step 2.2, when I change the hex to the generated INIT_CODE_PAIR_HASH, I get the error: "expected even number of hex-nibbles".

... in fact, if I use the code that appears in the guide, I also get the same error:

If I try to compile everything as is, the remix returns the same error:

I tried to get the '0x' from the start and everything worked correctly, I managed to start the project, but the exchange does not calculate the trade nor does it allow it to be done. The truth is that I do not know if this is the cause of the problem but it is the only error I had in the process.

When I start the project having bypassed the error, the Google Chrome console returns these errors:

From already thank you very much!

**Comment by laptrinhbockchain** [comment]
Please remove the two first  characters "0x" of INIT_CODE_PAIR_HASH

**Comment by gabenitez0** [comment]
> Please remove the two first characters "0x" of INIT_CODE_PAIR_HASH

Thanks for the answer, I did that and I get another error as I mentioned in the post. I am going to put together another post to consult it separately, here I leave this one in case someone has the same problem. Thanks!
