### ISSUE TITLE
Error: "Request failed. Network Error"

### ISSUE THREAD

**Issue by gabenitez0** [laptrinhbockchain/pancake-swap-v1-bsc-testnet#9]
Hi there!
I managed to install and follow all the steps correctly, but when I start it locally I get the following errors:
![image](https://user-images.githubusercontent.com/21694696/128874880-b5a40790-ce03-4ef5-bb12-61f50f0b19b0.png)

The contracts in the exchange load correctly, the problem is that it does not calculate the trade nor is it possible to do it.

From already thank you very much!

**Comment by laptrinhbockchain** [comment]
Pancake has just changed your API. You can see new API at:
– API v1: https://github.com/pancakeswap/pancake-info-api/blob/develop/v1-documentation.md
– API v2: https://github.com/pancakeswap/pancake-info-api/blob/develop/v2-documentation.md

New api to get price you can use:
– https://api.pancakeswap.info/api/tokens
– https://api.pancakeswap.info/api/v2/tokens

Now you can need to fix it in the file: src\hooks\useGetPriceData.ts

**Comment by laptrinhbockchain** [comment]
This error does not affect the swap feature.
